title: Frédéric HAUGUEL
email: hauguel.frederic
description: >- # this means to ignore newlines until "baseurl:"
  Ce site rassemble toutes mes connaissances et créations.
baseurl: "portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
